### ISSUE TITLE
[S] Simulate NAT IP pooling behaviour

### ISSUE THREAD

**Issue by henkberendsen** [hb140502/eduP2P_test_suite#2]
# Tasks
- [ ] Assign multiple IPs to each router in the simulated network setup
- [ ] Research types of RFC 4787 NAT pooling
- [ ] Decide which type(s) to implement in the test suite
- [ ] Implement these types in the NAT mapping and hairpinning scripts
- [ ] Investigate potential differences in system test results
- [ ] If differences are found, change expected test results to make tests pass again

# Description
Currently, each router in the simulated network setup is assigned one IP address. With NAT IP pooling, each new NAT mapping may choose from this pool of IP addresses. I suspect that the results of the extended system tests would be different if IP pooling were implemented in the test suite. Specifically, I expect that in some cases a direct connection can only be established if the same IP address would happen to be used for the connection to the peer and the STUN server, potentially making the test suite results non-deterministic depending on the IP pooling behaviour. If this is the case, a new test result code "TS_PASS" should be added to the system tests, which covers both the current result codes "TS_PASS_RELAY" and "TS_PASS_DIRECT".
